type CoupleCoupon {
  id: ID!
  title: String
  description: String
  expires: Date
  alreadyUsed: Boolean
  imgUrl: String
}

type Query {
   allCoupons: [CoupleCoupon!]
   couponsByUsed(alreadyUsed: Boolean!): [CoupleCoupon!]
}